{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ingress.name" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ template "server.name" . }}-service
            port:
              name: {{ template "server.port.name" . }}
      - path: /toposervice/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ template "toposervice.name" . }}-service
            port:
              name: {{ template "toposervice.port.name" . }}
{{- end }}
