---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mysql.name" . }}-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "mysql.name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "mysql.name" . }}
    spec:
      containers:
      - name: {{ template "mysql.name" . }}
        image: {{ .Values.mysql.image }}:{{ .Values.mysql.tag }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.rootPassword }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.databaseName }}
        ports:
        - containerPort: {{ .Values.mysql.port }}
        volumeMounts:
        - mountPath: /var/lib/{{ template "mysql.name" . }}
          name: datadb
      volumes:
      - name: datadb
        persistentVolumeClaim:
          claimName: {{ template "mysql.name" . }}-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mysql.name" . }}-pvc
spec:
  {{- if .Values.persistence.enabled }}
  storageClassName: {{ template "mysql.name" . }}
  {{- else }}
  storageClassName: {{ .Values.mysql.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "mysql.name" . }}-pv
spec:
  storageClassName: {{ template "mysql.name" . }}
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /db/{{ template "mysql.name" . }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql.name" . }}-service
  labels:
    app: {{ template "mysql.name" . }}
spec:
  ports:
  - port: {{ .Values.mysql.port }}
    targetPort: {{ .Values.mysql.port }}
    protocol: TCP
    name: {{ template "mysql.name" . }}-port
  selector:
    app: {{ template "mysql.name" . }}
  type: ClusterIP
---
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "mysql.name" . }}-from-{{ template "server.name" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "mysql.name" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "server.name" . }}
    ports:
    - port: {{ .Values.mysql.port }}
      protocol: TCP
{{- end }}
