---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rabbitmq.name" . }}-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "rabbitmq.name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "rabbitmq.name" . }}
    spec:
      containers:
      - name: {{ template "rabbitmq.name" . }}
        image: {{ .Values.rabbitmq.image }}:{{ .Values.rabbitmq.tag }}
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitmq.defaultUser }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.rabbitmq.defaultPassword }}
        ports:
        - containerPort: {{ .Values.rabbitmq.port }}
        - containerPort: {{ .Values.rabbitmq.consoleport }}
        volumeMounts:
        - mountPath: /var/lib/{{ template "rabbitmq.name" . }}/mnesia
          name: datarabbit
      volumes:
      - name: datarabbit
        persistentVolumeClaim:
          claimName: {{ template "rabbitmq.name" . }}-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "rabbitmq.name" . }}-pvc
spec:
  {{- if .Values.persistence.enabled }}
  storageClassName: {{ template "rabbitmq.name" . }}
  {{- else }}
  storageClassName: {{ .Values.rabbitmq.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "rabbitmq.name" . }}-pv
spec:
  storageClassName: {{ template "rabbitmq.name" . }}
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /db/{{ template "rabbitmq.name" . }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq.name" . }}-service
  labels:
    app: {{ template "rabbitmq.name" . }}
spec:
  ports:
  - port: {{ .Values.rabbitmq.port }}
    targetPort: {{ .Values.rabbitmq.port }}
    protocol: TCP
    name: {{ template "rabbitmq.name" . }}-port-{{ .Values.rabbitmq.port }}
  - port: {{ .Values.rabbitmq.consoleport }}
    targetPort: {{ .Values.rabbitmq.consoleport }}
    protocol: TCP
    name: {{ template "rabbitmq.name" . }}-port-{{ .Values.rabbitmq.consoleport }}
  selector:
    app: {{ template "rabbitmq.name" . }}
  type: ClusterIP
---
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "rabbitmq.name" . }}-from-planner-{{ template "server.name" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "rabbitmq.name" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "planner.name" . }}
    - podSelector:
        matchLabels:
          app: {{ template "server.name" . }}
    ports:
    - port: {{ .Values.rabbitmq.port }}
      protocol: TCP
{{- end }}
