---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "weatherservice.name" . }}-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "weatherservice.name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "weatherservice.name" . }}
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
      - name: {{ template "weatherservice.name" . }}
        image: {{ .Values.weatherservice.image }}:{{ .Values.weatherservice.tag }}
        env:
        - name: GRPC_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GRPC_PORT
          value: {{ .Values.weatherservice.port | quote}}
        ports:
        - containerPort: {{ .Values.weatherservice.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "weatherservice.name" . }}-service
  labels:
    app: {{ template "weatherservice.name" . }}
spec:
  ports:
  - port: {{ .Values.weatherservice.port }}
    targetPort: {{ .Values.weatherservice.port }}
    protocol: TCP
    name: weather-port
  selector:
    app: {{ template "weatherservice.name" . }}
  type: ClusterIP
---
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "weatherservice.name" . }}-from-planner
spec:
  podSelector:
    matchLabels:
      app: {{ template "weatherservice.name" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "planner.name" . }}
    ports:
    - port: {{ .Values.weatherservice.port }}
      protocol: TCP
{{- end }}
